version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./.env

  backend:
    build: ./TestParser
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static:
  media: